
import { Calculator, ShoppingCart, Utensils, Microscope, Leaf } from 'lucide-react';
import { FamilyQuestProps } from './FamilyQuestCard';

export const familyQuestsData: FamilyQuestProps[] = [
  {
    id: '1',
    title: 'Kitchen Math Master',
    description: 'Measure ingredients and calculate proportions with your family to make a delicious recipe together!',
    category: 'Weekly',
    subjects: ['Math', 'Home Science'],
    duration: '45 min',
    members: '2+',
    difficulty: 'Easy',
    xp: 50,
    progress: 25,
    icon: <Utensils size={20} />,
    deadline: 'Sunday',
    isNew: true,
  },
  {
    id: '2',
    title: 'Plan a ₹500 Family Outing',
    description: 'Create a budget for a family day out. Compare prices, calculate expenses, and make decisions together!',
    category: 'Weekly',
    subjects: ['Math', 'Economics'],
    duration: '60 min',
    members: 'All',
    difficulty: 'Medium',
    xp: 75,
    progress: 0,
    icon: <ShoppingCart size={20} />,
    deadline: 'Monday',
  },
  {
    id: '3',
    title: 'Plant a Family Garden',
    description: 'Learn about plant life cycles, measure growth, and document your observations as a family science project!',
    category: 'Monthly',
    subjects: ['Science', 'Environmental Studies'],
    duration: '2-4 weeks',
    members: '2+',
    difficulty: 'Medium',
    xp: 150,
    progress: 0,
    icon: <Leaf size={20} />,
    deadline: 'Next Month',
  },
  {
    id: '4',
    title: 'Home Science Lab',
    description: 'Conduct simple experiments at home with everyday materials. Learn scientific principles as a family!',
    category: 'Premium',
    subjects: ['Science', 'Chemistry'],
    duration: '90 min',
    members: '2+',
    difficulty: 'Hard',
    xp: 100,
    progress: 0,
    icon: <Microscope size={20} />,
    deadline: 'Next Week',
    isLocked: true,
  },
];
